### ISSUE TITLE
Could you add an option in which the module will be resolved?

### ISSUE THREAD

**Issue by Alex1990** [van-nguyen/webpack-cdn-plugin#12]
I came across a situation where need to make the `WebpackCdnPlugin.node_modules` as an option.

I use lerna to manage multiple packages.

```
--  projectRoot/
  -- packages/
    -- app-one/
      -- node_mdoules/
        -- build-tool/ (symlink to ../../build-tool)
    -- build-tool/
      -- node_modules/
        -- webpack-cdn-plugin/
```

So, The `WebpackCdnPlugin.node_modules` will be `build-tool/node_modules`, but I need it to be `app-one/node_modules`。

**Comment by van-nguyen** [comment]
Hi @Alex1990, I can see the use case for it and acknowledged there is a gap. Currently it only assumes the node_modules in the project root level. A PR is always welcome. Having said that I would be happy to take a look otherwise.

Cheers,
Van

**Comment by Alex1990** [comment]
Currently I can use the below code.

```
WebpackCdnPlugin.node_modules = path.join(process.cwd(), 'node_modules');
```
