### ISSUE TITLE
Missing `crossorigin` attribute

### ISSUE THREAD

**Issue by myst729** [van-nguyen/webpack-cdn-plugin#14]
For scripts from another origin, captured JS errors have no helpful information - just an ambiguous 'Script error'. To deal with this, a [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) attribute is introduced.

For example:

```html
<script src="https://unpkg.com/vue@2.5.13/dist/vue.min.js" crossorigin="anonymous"></script>

<!-- or just omit the value -->
<script src="https://unpkg.com/vue-router@3.0.1/dist/vue-router.min.js" crossorigin></script>
```

**Comment by van-nguyen** [comment]
@myst729 not sure if we need this if you don’t use protocol in our urls. e.g

`<script src="//unpkg.com/vue-router@3.0.1/dist/vue-router.min.js"></script>`

Please let me know if this is not true and I’ll look into it. Thanks for reporting.

**Comment by myst729** [comment]
No, it's not about protocol. I have a sentry service to capture production exceptions.

Say, the app is hosted under **a.com**, and it loads scripts from **unpkg.com** cdn. So no matter http or https, the scripts are cross origin.

If the `crossorigin` attributes are provided, the errors thrown by scripts from unpkg will be captured with meaningful information such as error stack, line and column number, etc. Without `crossorigin`, the only information is the phrase `Script error`, doesn't help at all.

So this is what I want. Because scripts from CDN are not only those well-crafted libs like Vue, there are also libs by myself. I want to be aware if they don't work.

**Comment by van-nguyen** [comment]
@myst729 Sorry for getting back to you late, just got back from my holiday. I had a look at this, but seems quite difficult to fix it without doing a PR to `HtmlWebpackPlugin`. I will look into this further, unless you can help with this?

**Comment by van-nguyen** [comment]
Seems this is an upstream issue for `HtmlWebpackPlugin`, closing.

**Comment by myst729** [comment]
This looks like doable. https://github.com/waysact/webpack-subresource-integrity/blob/master/index.js#L265

**Comment by myst729** [comment]
The whole mechanism of Webpack is a bit complicated, but I think I finally make it.

This is the solution for v1.x (works with Webpack 3 and lower): https://github.com/myst729/webpack-cdn-plugin/commit/c329271d029f107ff71b0542f092b00a24e7938d For Webpack 4 just use Tappable API, I'll make a PR later.

However I haven't found an approach to distinguish crossorigin resources from those of the same origin, so all `link` and `script` tags will have that attribute (doesn't matter for resources from the same origin though):

```html
<script type=text/javascript src=//unpkg.com/vue@2.5.16/dist/vue.runtime.min.js crossorigin=anonymous></script>
<script type=text/javascript src=//unpkg.com/element-ui@2.4.3/lib/index.min.js crossorigin=anonymous></script>
<script type=text/javascript src=/static/js/app.3fa5813ddded3e93a56d.js crossorigin=anonymous></script>
```

I leaf a TODO on [line 70](https://github.com/myst729/webpack-cdn-plugin/commit/c329271d029f107ff71b0542f092b00a24e7938d#diff-1a7639840c1699303af8d03d6672c403R70), any ideas?

**Comment by myst729** [comment]
Could you create a "legacy" branch from v1.x? So that I could send a PR, since some developers are still using Webpack 3.x.

**Comment by van-nguyen** [comment]
Hi @myst729 thanks for the PR, regarding the legacy branch seems like a good idea. I'm not sure how much is involved with backporting all the features, since I'm not using v3 of webpack anymore I wouldn't be able to support it fully, are you able to help with maintaining it? I've pushed a legacy branch.
