### ISSUE TITLE
Feature: multiple styles

### ISSUE THREAD

**Issue by jfrs** [van-nguyen/webpack-cdn-plugin#15]
I'm using `vue-material` and the default themes are located in separate files, it would be useful to have a way of specifying more than one, perhaps something like `styles`:`array`.

**Comment by van-nguyen** [comment]
@jfrs sorry for getting back to you late, have only got back from my holiday.

That seems like a good feature to add. Are you able to assist with a PR if this is urgent to your needs? Otherwise I will have a look at it this week when I have some spare time.

**Comment by jfrs** [comment]
No worries, I've migrated to webpack 4 in the meantime so it's not urgent.
I had a look at the code but I couldn't come up with anything, I have very limited knowledge in that area.
