### ISSUE TITLE
Different directory name on cloudflare

### ISSUE THREAD

**Issue by screendriver** [van-nguyen/webpack-cdn-plugin#2]
For example

```js
new WebpackCdnPlugin({
  modules: [
    { name: 'moment' },
  ],
  prod: true,
  prodUrl: 'https://cdnjs.cloudflare.com/ajax/libs/:name/:version/:path',
  publicPath: '/node_modules',
}),
```

Generates `https://cdnjs.cloudflare.com/ajax/libs/moment/2.18.1/moment.js`
Unfortunately the correct URL is `https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js`

As you can see the name is different: instead of `/moment/` (the directory in `node_modules` is correct) it is `/moment.js/`

How can I solve this?

**Comment by van-nguyen** [comment]
Unfortunately this plugin only supports CDNs that follows npm structure, cloudflare should fix this if they care about consistency. A workaround would be to creat an alias npm package that cloudflare is using for now. I would have to see how much complexity this will add to the codebase if an extra option is introduced.

**Comment by screendriver** [comment]
> Unfortunately this plugin only supports CDNs that follows npm structure, cloudflare should fix this if they care about consistency.

No. Every CDN out there has a different structure and none of them has / should have the npm structure. The only one that has this is `unpgk.com`. For example the Google CDN for AngularJS looks like https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js As you can see there is a `/angularjs/` in the path and the filename is `angular.min.js` (without `.js`)

**Comment by van-nguyen** [comment]
Understood, seems an extra option to specify a mapping name is inevitable.
