### ISSUE TITLE
"optimize" not actually published

### ISSUE THREAD

**Issue by gaje** [van-nguyen/webpack-cdn-plugin#27]
The option to optimize is there in the source code, but v2.1.0 does not contain that code.

Can this feature be published?

**Comment by van-nguyen** [comment]
Hi @gaje sorry was quite busy during the week, will publish it now. Please me know if it works alright.

**Comment by van-nguyen** [comment]
@gaje is it working okay?

**Comment by van-nguyen** [comment]
@gaje sounds good to me, mind doing a PR?
