### ISSUE TITLE
How to write in vue.config.js?

### ISSUE THREAD

**Issue by neciszhang** [van-nguyen/webpack-cdn-plugin#28]
hello,
       you are awesome! I am use vue-cli 3.0 ,but i don't know how to write your plugin in "vue.config.js".
Can you provide examples to write config in it? Thanks a lot!

**Comment by neciszhang** [comment]
hello==

**Comment by van-nguyen** [comment]
Hi @neciszhang I'm really sure as I don't use Vue, saw this article https://cli.vuejs.org/guide/webpack.html seems like it is just an abstraction of the webpack config. You can pass this plugin along with html plugin, please refer to the examples in this repo. Hope this helps.

**Comment by neciszhang** [comment]
@van-nguyen  Thank you very much! I write your config in "chainWebpack" like
`"config.plugin('webpack-cdn-plugin').use(WebpackCdnPlugin, [{
        modules: [{
          name: 'vue',
          var: 'Vue',
          path: 'vue.min.js'
        },")   `  
I use it successfully.Thank you for providing this plugin!
