### ISSUE TITLE
How to add .min.js?

### ISSUE THREAD

**Issue by screendriver** [van-nguyen/webpack-cdn-plugin#3]
For example

```js
new WebpackCdnPlugin({
  modules: [
    { name: 'moment', path: isDev ? 'moment.js' : 'moment.min.js' },
  ],
  prod: true,
  prodUrl: 'https://cdnjs.cloudflare.com/ajax/libs/:name/:version/:path',
  publicPath: '/node_modules',
}),
```

Generates `https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js` Apart from #2 (wrong directory path): how can I append `.min.js` in production build?

Maybe so?

```js
new WebpackCdnPlugin({
  modules: [
    { name: 'moment', path: isDev ? 'moment.js' : 'moment.min.js' },
  ],
  prod: true,
  prodUrl: 'https://cdnjs.cloudflare.com/ajax/libs/:name/:version/:path',
  publicPath: '/node_modules',
}),
```

This would be really cumbersome because I have to add the ternary operator to every module.

**Comment by van-nguyen** [comment]
@screendriver Question is why would you want the non-minified version in dev?

**Comment by van-nguyen** [comment]
Actually I found a workaround for you:
'''js
{
devUrl: '/:name/:path.js',
prodUrl: 'https://cdnjs.cloudflare.com/ajax/libs/:name/:version/:path.min.js'
}
'''

Then just remove the .js and .min.js in your path.

**Comment by screendriver** [comment]
> [@screendriver](https://github.com/screendriver) Question is why would you want the non-minified version in dev?

Because there are libraries, like React for example, that give you debug output (like wrong PropTypes) while in development. These are removed in production builds. Also I want to debug some libraries if I found a bug in there.

**Comment by van-nguyen** [comment]
Does the solution above work for you? If so can I close this issue? Thanks for reporting.
