### ISSUE TITLE
If cssOnly is true, the name should not be assigned to the module in global scope.

### ISSUE THREAD

**Issue by ibufu** [van-nguyen/webpack-cdn-plugin#33]
If cssOnly is true, the name should not be assigned to the module in global scope.

**Comment by doveccl** [comment]
Same problem occurs to me

My project requires `highlight.js`
```js
{ name: 'highlight.js', cssOnly: true, style: 'styles/github.css' }
```
The configuration above throws error `Uncaught ReferenceError: highlight is not defined` because it was assigned to the module `module.exports = highlight.js`

@van-nguyen Please consider ignore externals when `cssOnly` is true
