### ISSUE TITLE
How about compiling with buble/babel before npm publish?

### ISSUE THREAD

**Issue by xiaoiver** [van-nguyen/webpack-cdn-plugin#4]
Sometimes we need to run webpack on node 4.x. But some syntax like destructuring assignment will throw an error.

**Comment by van-nguyen** [comment]
As mentioned in https://github.com/van-nguyen/webpack-cdn-plugin/pull/5 if we want to support legacy system, I think it should be done silently. i.e. only do this when node < 6. Thoughts?

**Comment by van-nguyen** [comment]
PR merged

**Comment by van-nguyen** [comment]
Hi @xiaoiver I think found an elegant solution for this https://github.com/van-nguyen/webpack-cdn-plugin/compare/07275714118a7f55870d00a9ddc0059f4d0e1885...master

Mainly use babel to compile using "current" node version. Have it run when module is installed, require from "main" and "module" now has different concerns. What do you think of this?
