### ISSUE TITLE
Current latest version breaks commonJS example on README

### ISSUE THREAD

**Issue by thethomaseffect** [van-nguyen/webpack-cdn-plugin#43]
As the latest version uses ES6 modules, the commonJS code in the example does not work.

```javascript
const WebpackCdnPlugin = require('webpack-cdn-plugin');
// ...
new WebpackCdnPlugin({});
```

now yields `TypeError: WebpackCdnPlugin is not a constructor`

The fix is to change the import to:

```javascript
const WebpackCdnPlugin = require('webpack-cdn-plugin').default;
```

It might be just easier to change your examples to ES6+ though.

**Comment by van-nguyen** [comment]
Hi @thethomaseffect thanks for reporting this, upon upgrading to babel 7 I forgot to also add in `babel-plugin-add-module-exports` which is meant to fix this situation. It is now resolved.
